### ISSUE TITLE
should users be able to export downloaded mods right now I made a full system to not allow that. [They Should]

### ISSUE THREAD

**Issue by MohammedGamer85** [MohammedGamer85/MythosApp#10]

**Comment by MohammedGamer85** [comment]
by Downloaded mods meaning mods from mythos.

**Comment by Ikethepro18** [comment]
I don't see any reason why this should be the case. The export function essentially just adds the mod to a renamed zip file, which any user can simply download directly from Mythos or do themselves. It's a lot of work for something that's not necessary and that can be easily bypassed, I think it warrants removal

**Comment by MohammedGamer85** [comment]
Users will have the ability to export downloaded mods in 0.0.2.1 or 0.2.2/BETA0.1.0.0.
this will be closed when it is done.

**Comment by MohammedGamer85** [comment]
Done.
