### ISSUE TITLE
Add open in file explorer to myths (suggestion)

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#35]
Add a button to the installed myth page which, when clicked opens the myth in file explorer. Could be tricky given myths have an RP and a BP so maybe open both and have an option in settings where users can choose to open just the RP, just the BP or RP and BP (default)

_The open folder button displayed bottom right_
![image](https://i.imgur.com/Dk0G41U.png)

_The new 'Myth Open Folder Behaviour' setting displayed at the bottom_
![image](https://i.imgur.com/DhXXeAE.png)

**Comment by MohammedGamer85** [comment]
Simple will be added in 0.0.1.2
