### ISSUE TITLE
Myths don't load LongDescription

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#36]
Despite having a LongDescription (shown as 'About this Myth' on the website) it is not shown in the app, instead saying 'There is no LongDescription'

'About this Myth' on the website
![](https://i.imgur.com/ezvK7Tf.png)

LongDescription in the app
![](https://i.imgur.com/JsfBc8W.png)

**Comment by MohammedGamer85** [comment]
you can check if that issue
continues by deleting the importedmods.json file which will allow you to install the mod again

**Comment by MohammedGamer85** [comment]
work for for the person who will fix this: make it so when a mod is install it is given a randomly generated UUID that has nothing todo with the mod uuid to allow the user to install two of the same mod without them overriding each other

**Comment by Ikethepro18** [comment]
The description loads on the discovery page preview, but not when you click on it to see and download the mod
![](https://i.imgur.com/0qoSD6r.png)

 Once downloaded and in the Home page, the description still isn't loaded
 ![](https://i.imgur.com/aHj0sl7.png)

I deleted the `importedMods.json` file and deleted the mod file from the `DownLoaded` folder

**Comment by MohammedGamer85** [comment]
@Ikethepro18

**Comment by Ikethepro18** [comment]
I don't know what more to tell you. I've tried deleting the whole `Mythos` folder from my documents but the issue persists

**Comment by MohammedGamer85** [comment]
> I don't know what more to tell you. I've tried deleting the whole `Mythos` folder from my documents but the issue persists

trying to fix the issue right now but just so you know it will create even more bugs for your to find. as to fix it i needed to change the value of one of the variables from a DataTIme to a string so we will have allot of crachs from convention erros

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/db845de6-e551-4839-8df9-0d69624d4c6f)

**Comment by MohammedGamer85** [comment]
LETS GO MOD DOWNLOADING NO LONGER WORKS. technically the bug is fixed but still keep this open till all the know bugs created by it are fixed too.

**Comment by MohammedGamer85** [comment]
FIXED and resolved
