### ISSUE TITLE
work for for the person who will fix this: make it so when a mod is install it is given a randomly generated UUID that has nothing todo with the mod uuid to allow the user to install two of the same mod without them overriding each other

### ISSUE THREAD

**Issue by MohammedGamer85** [MohammedGamer85/MythosApp#37]
work for for the person who will fix this: make it so when a mod is install it is given a randomly generated UUID that has nothing todo with the mod uuid to allow the user to install two of the same mod without them overriding each other

_Originally posted by @MohammedGamer85 in https://github.com/MohammedGamer85/MythosApp/issues/36#issuecomment-1691818221_

**Comment by Ikethepro18** [comment]
Under what circumstance would a user want to install a mod twice? And how would that be handled by the app, list it twice in the Home page? I think this is an interesting idea but it would require more exploring first

**Comment by MohammedGamer85** [comment]
right now what would happen if you istall a mod twice is it will show in the homepage twice but they will still reference the same files

> Under what circumstance would a user want to install a mod twice? And how would that be handled by the app, list it twice in the Home page? I think this is an interesting idea but it would require more exploring first

@Ikethepro18

**Comment by MohammedGamer85** [comment]
does not happen as of #41

**Comment by MohammedGamer85** [comment]
happens as of #41 being fixed.

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/f7c4b53c-ae67-4a36-a24a-3955d706b27e)
okay mohammed DEAL WITH IT.
