### ISSUE TITLE
Files aren't cleared from Temp

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#39]
The `Temp` folder stores mods when they are downloaded and then extracted to the `DownLoaded` folder. Presumably, the mod is then supposed to be deleted from `Temp` as it is no longer needed, but this does not happen

**Comment by MohammedGamer85** [comment]
@Ikethepro18 what is left is the mod.zip right

**Comment by Ikethepro18** [comment]
The whole contents of the mod (RP and BP)

**Comment by MohammedGamer85** [comment]
FIXED. i had written `Directory.Delete(Path.combine(filepath, "Mod.zip"))` instead of `File.Delete(Path.Combine(filepath, "Mod.zip")) `
