### ISSUE TITLE
modinfo.json gives mods a UUID for BP/RP even if it doesn't have one

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#40]
Not all mods have a BP and an RP. Despite this, the app gives the mod a UUID for it's BP and RP. This is most notable for skin mods as they don't have a BP. This is minor and doesn't effect anything but I thought it bore mention

**Comment by MohammedGamer85** [comment]
https://github.com/MohammedGamer85/MythosApp/issues/37 this also relates to the fact that the system will be changed later any way.

**Comment by MohammedGamer85** [comment]
https://github.com/MohammedGamer85/MythosApp/issues/34 also this full system needs to be redone as i ahve over 5 issues here on it.

**Comment by MohammedGamer85** [comment]
There was not a problem there was just work to be done and now it is done.
