### ISSUE TITLE
Mod exporting produces `.mclMod` rather than `.mclmod`

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#46]
When a mod is exported, it is given the extension `.mclMod` when it's expected that it would have the extension `.mclmod`

These are functionally identical, but I think the capitalisation should be consistent aka no capitalisation at all

**Comment by MohammedGamer85** [comment]
Agreed and I remember going into the code to fix that at some point but hot side ttacked

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/6093e007-d74c-42db-a737-9b88a3089108)
 FIXED was very simple. as expected
