### ISSUE TITLE
Import and Export Myth should be Import and Export Mod

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#47]
The Import _Myth_ and Export _Myth_ functions would indicate to users that they can only import and export Myths and not all types of mods like resource packs and skin packs. It should be tweaked to be Import _Mod_ and Export _Mod_

**Comment by MohammedGamer85** [comment]
They can export skin packs

**Comment by MohammedGamer85** [comment]
And no has made a rp in my knowledge so idk if it would work for it

**Comment by Ikethepro18** [comment]
Yeah I'm just saying it might be a good idea to change the name to avoid confusion

**Comment by MohammedGamer85** [comment]
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/6da02c3e-8768-43b2-bb19-af5a943017b1)
a Failed message should do till i know if it can export and import resource packs or no. [will still keep this issue open]
