### ISSUE TITLE
Search doesn't work. MAKE IT WORK [EDIT: by mohammed]

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/MythosApp#48]
I assume it's just not been developed yet but thought I'd mention it anyways in case it was instead bugged or something

**Comment by MohammedGamer85** [comment]
Oh well forgot to do this
![image](https://github.com/MohammedGamer85/MythosApp/assets/100155245/2373df3f-7126-4592-92e2-35adf87bab79)

**Comment by MohammedGamer85** [comment]
there it says it does not work.

**Comment by MohammedGamer85** [comment]
that was a early revision.

**Comment by MohammedGamer85** [comment]
to be done when we are in beta.

**Comment by MohammedGamer85** [comment]
TOOK A WHILE BUT here we go made it for home page and discover page
![Animation1](https://github.com/MohammedGamer85/MythosApp/assets/100155245/4df367d8-f8e9-4061-87f4-98aa2f2d7d95)
